
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 11;
  public static final int BOX = 7;
  public static final int SATIS = 4;
  public static final int NOM = 13;
  public static final int RPARAN = 3;
  public static final int LPARAN = 2;
  public static final int EOF = 0;
  public static final int DIA = 6;
  public static final int IMP = 8;
  public static final int error = 1;
  public static final int NOT = 10;
  public static final int BIIMP = 9;
  public static final int OR = 12;
  public static final int PROP = 14;
  public static final int E = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPARAN",
  "RPARAN",
  "SATIS",
  "E",
  "DIA",
  "BOX",
  "IMP",
  "BIIMP",
  "NOT",
  "AND",
  "OR",
  "NOM",
  "PROP"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[11]=new String("AND");
		TT[7]=new String("BOX");
		TT[4]=new String("SATIS");
		TT[13]=new String("NOM");
		TT[3]=new String("RPARAN");
		TT[2]=new String("LPARAN");
		TT[0]=new String("EOF");
		TT[6]=new String("DIA");
		TT[8]=new String("IMP");
		TT[1]=new String("error");
		TT[10]=new String("NOT");
		TT[9]=new String("BIIMP");
		TT[12]=new String("OR");
		TT[14]=new String("PROP");
		TT[5]=new String("E");
	}
public String getTT(int i){return TT[i];}
}

